export const api_url = 'http://logomokup.com/api/'
export const img_url = 'http://logomokup.com/uploads/'
export const chat_icon = img_url + 'chat_icons/patient.png'
// export const vendor_category = "vendor/category";
// export const sub_category = "vendor/sub_category";
// export const faq = "customer/faq";
// export const privacy = "privacy_policy";
// export const products = "vendor/products";
// export const search_products = "search_products";
// export const related_products = "related_products";
export const register_url = 'customer'
export const login_url = 'customer/login'
// export const address = "address";
// export const address_list = "address/all";
// export const address_delete = "address/delete";
export const doctorthree = require('../assets/img/doctorthree.jpg')
export const my_orders = 'customer/bookings'
// export const order_details = "customer/order_details";
export const booking_details = 'customer/booking_details'
// export const promo_code = "promo";
export const get_profile = 'customer/get_profile'
export const image_upload = 'image_upload'
export const profile_update = 'customer/profile_update'
export const home_details = 'customer/home'
export const create_booking = 'customer/create_booking'
export const check_available_timing = 'customer/check_available_timing'
export const get_doctor_by_services = 'get_doctor_by_services'
export const get_access_token_for_video = 'get_access_token_for_video'
export const get_blood_list = 'blood_group'
export const chat_pusher = 'chat_pusher'
export const font_description = 'GoogleSans-Medium'
export const font_title = 'GoogleSans-Bold'
